(require 'arche-prog)
(require 'arche-package)

(use-package haskell-mode)

(add-hook 'haskell-mode-hook
          (lambda ()
            (push '("()" . ?∅) prettify-symbols-alist)
            (push '("\\" . ?λ) prettify-symbols-alist)
            (push '("pi" . ?π) prettify-symbols-alist)
            (push '("=>" . ?⇒) prettify-symbols-alist)
            (push '("->" . ?→) prettify-symbols-alist)
            (push '("<-" . ?←) prettify-symbols-alist)
            (push '("<=" . ?≤) prettify-symbols-alist)
            (push '(">=" . ?≥) prettify-symbols-alist)
            (push '("==" . ?≡) prettify-symbols-alist)
            (push '("/=" . ?≢) prettify-symbols-alist)
            (push '("!!" . "‼") prettify-symbols-alist)
            (push '("&&" . ?∧) prettify-symbols-alist)
            (push '("||" . ?∨) prettify-symbols-alist)
            (push '("~>" . ?⇝) prettify-symbols-alist)
            (push '("-<" . ?↢) prettify-symbols-alist)
            (push '("not" . ?¬) prettify-symbols-alist)
            (push '("forall" . ?∀) prettify-symbols-alist)
            (push '("sqrt" . ?√) prettify-symbols-alist)
            (push '("undefined" . ?⊥) prettify-symbols-alist)
            (prettify-symbols-mode)))

(provide 'arche-haskell)
